name: Testing for basic hello world shell scripting 

on:
  push:
    branches:
      - Project1
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run Hello World Script
        run: |
          echo "Hello, World! from DIM team"